version: '3'
services:
  app:
    build: ./api
    ports:
      - "3000:3000"
    #depends_on:
    #  - mongo
    volumes:
      - "./api/:/usr/src/app"
      - "reserved:/usr/src/app/node_modules"
  #mongo:
  #  image: "mongo" 
  #  ports:
  #    - "27017:27017"
volumes:
  reserved: