version: '3'
services:
  api:
    build: ./api
    #command: /usr/src/app/node_modules/.bin/nodemon index.js
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks: 
      - backend
    volumes:
      - "./api/:/usr/src/app"
      - "reserved:/usr/src/app/node_modules"
  app:
    build: ./app
    ports:
      - 8080:80
    networks: 
      - backend
    volumes:
      - "./app/dist:/usr/share/nginx/html"

  database:
    image: "mongo" 
    #ports:
    #  - "27017:27017"
    networks: 
      - backend
    environment:
      - MONGO_INITDB_DATABASE=asksforyou

volumes:
  reserved:

networks:
  backend: